services:
  # Database Service
  db:
    image: postgres:15-alpine
    container_name: devops-db
    environment:
      POSTGRES_USER: devops_user
      POSTGRES_PASSWORD: devops_password
      POSTGRES_DB: devops_db
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U devops_user" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - devops_network

  # Backend Service
  backend:
    image: saikiranasamwar4/task-manager-backend:latest
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: devops-backend
    environment:
      FLASK_ENV: production
      DATABASE_URL: postgresql://devops_user:devops_password@db:5432/devops_db
    ports:
      - "0.0.0.0:5000:5000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - devops_network

  # Frontend Service (Nginx)
  frontend:
    image: saikiranasamwar4/task-manager-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: devops-frontend
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    environment:
      API_URL: http://backend:5000
    depends_on:
      - backend
    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - devops_network

volumes:
  db_data:


networks:
  devops_network:
    driver: bridge
