apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: task-manager
type: Opaque
stringData:
  POSTGRES_USER: devops_user
  POSTGRES_PASSWORD: devops_password
  POSTGRES_DB: devops_db
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: task-manager
data:
  FLASK_ENV: "production"
  DATABASE_URL: "postgresql://devops_user:devops_password@postgres-service:5432/devops_db"
