apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: task-manager
type: Opaque
stringData:
  POSTGRES_USER: devops_user
  POSTGRES_PASSWORD: devops_password
  POSTGRES_DB: devops_db
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: task-manager
type: Opaque
stringData:
  DATABASE_URL: "postgresql://devops_user:devops_password@postgres-service:5432/devops_db"
  SECRET_KEY: "change-this-to-random-secret-key-in-production"
